language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.5
notifications:
    email: false
addons:
  ssh_known_hosts:
    - bitbucket.org
  apt:
      packages:
          - libhdf5-serial-dev

before_install:
    - pip install pycodestyle
    - pip install future
    - pip install pytest

install:
    - pip install -r requirements.txt
    - pip install .

script:
    # Run pep8 on all .py files in all subfolders
    - find . -name \*.py -exec pycodestyle {} +
    - pytest test
    - python3 test/make_test_swarm.py tmp 1
    - scripts/dias -c tmp/dias.conf configtest
    - script/dias -c tmp/dias.conf tryrun task0
