language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6
notifications:
    email: false
addons:
  ssh_known_hosts:
    - bitbucket.org
  apt:
      packages:
          - libhdf5-serial-dev
          - graphviz  # needed for the sphinx build
          - libopenmpi-dev
          - openmpi-bin


before_install:
    - pip install black
    - pip install future
    - pip install pytest
    -
install:
    - pip install -r docs/rtd-requirements.txt
    - pip install sphinx==2.4.4
    - pip install .

script:
    # Run black on all .py files in all subfolders
    - black --check .

    # Run pydocstyle on all .py files
    - find . -name \*.py ! -name 'versioneer.py' ! -name '_version.py' -exec pydocstyle --convention=numpy {} +

    # Run all tests in test folder
    - pytest --ignore dias/analyzers/test_analyzer.py

    # Test configs. Also imports analyzers and finds import errors (like missing requirements).
    - python scripts/dias -c conf/dias.conf configtest

    # test dias script
    - python test/make_test_swarm.py test_conf 1
    - python scripts/dias -c test_conf/dias.conf configtest
    - python scripts/dias -c test_conf/dias.conf tryrun task0

    # Build docs
    - cd docs
    - make html
